package Algoga.server.domain.member;

public enum Country {
    Korea,      // 한국
    China,      // 중국
    Japan,      // 일본
    Usa,        // 미국
    Taiwan,     // 대만
    Thailand,   // 태국
    Vietnam,    // 베트남
    Philippines, // 필리핀
    Malaysia,   // 말레이시아
    Singapore,  // 싱가포르
    Indonesia,  // 인도네시아
    HongKong,   // 홍콩
    Australia,  // 호주
    Canada,     // 캐나다
    Russia,     // 러시아
    Mongolia,   // 몽골
    India,      // 인도
    UnitedKingdom, // 영국
    Germany,    // 독일
    France,     // 프랑스
    Italy,      // 이탈리아
    Spain,      // 스페인
    Netherlands, // 네덜란드
    Switzerland, // 스위스
    Sweden,     // 스웨덴
    Norway,     // 노르웨이
    Denmark,    // 덴마크
    Finland,    // 핀란드
    Austria,    // 오스트리아
    Belgium,    // 벨기에
    CzechRepublic, // 체코
    Poland,     // 폴란드
    Turkey,     // 터키
    UnitedArabEmirates, // 아랍에미리트
    Qatar,      // 카타르
    SaudiArabia, // 사우디아라비아
    Kazakhstan, // 카자흐스탄
    Uzbekistan, // 우즈베키스탄
    NewZealand, // 뉴질랜드
    Brazil,     // 브라질
    Mexico,     // 멕시코
    Argentina,  // 아르헨티나
    Chile,      // 칠레
    SouthAfrica, // 남아프리카공화국
    Egypt,      // 이집트
    Morocco,    // 모로코
    Israel,     // 이스라엘
    Myanmar,    // 미얀마
    Cambodia,   // 캄보디아
    Laos,       // 라오스
    Nepal       // 네팔
}
